; PlatformIO Project Configuration File
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

; Libraries using GitHub URLs
lib_deps = 
    https://github.com/chris--a/Keypad.git
    https://github.com/marcoschwartz/LiquidCrystal_I2C.git
    https://github.com/jarzebski/Arduino-INA226.git
    https://github.com/mobizt/ESP-Google-Sheet-Client.git
    bblanchon/ArduinoJson @ 6.21.5